# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    # Note that we use 3.12 here rather than 3.13 to avoid spurious Sphinx errors
    # about not being able to link to `pathlib._locals.Path`.
    python: "3.12"

sphinx:
  configuration: documentation/source/conf.py
  builder: "html"
  fail_on_warning: true

python:
   install:
    - requirements: requirements-doc.txt
