# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    # Fix LFS images. See documentation at:
    # https://docs.readthedocs.com/platform/stable/build-customization.html#support-git-lfs-large-file-storage
    post_checkout:
      # Download and uncompress the binary
      # https://git-lfs.github.com/
      - wget https://github.com/git-lfs/git-lfs/releases/download/v3.6.1/git-lfs-linux-amd64-v3.6.1.tar.gz
      - tar xvfz git-lfs-linux-amd64-v3.6.1.tar.gz  # cspell:disable-line
      # Modify LFS config paths to point where git-lfs binary was downloaded
      - git config filter.lfs.process "`pwd`/git-lfs-3.6.1/git-lfs filter-process"
      - git config filter.lfs.smudge  "`pwd`/git-lfs-3.6.1/git-lfs smudge -- %f"
      - git config filter.lfs.clean "`pwd`/git-lfs-3.6.1/git-lfs clean -- %f"
      # Make LFS available in current repository
      - ./git-lfs-3.6.1/git-lfs install
      # Download content from remote
      - ./git-lfs-3.6.1/git-lfs fetch
      # Make local files to have the real content on them
      - ./git-lfs-3.6.1/git-lfs checkout
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
      # We use the `--frozen` option instead of `--locked`, as we want RTD to build the
      # documentation according to the repository state, even if `uv.lock` is outdated.
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --extra doc --no-dev --frozen

sphinx:
  configuration: documentation/source/conf.py
  builder: "html"
  fail_on_warning: true
