words:
  [
    "GCHQ",
    "coreax",
    "coreset",
    "Approximator",
    "Optimiser",
    "Normalised",
    "pytest",
    "mathbb",
    "optimisations",
    "Licence",
    "minimise",
    "docstrings",
    "Prioritise",
    "quickstart",
    "pcimq",
    "triu",
    "automodule",
    "booktitle",
    "Frobenius",
    "imshow",
    "ndim",
    "mimsave",
    "optimallyweighted",
    "nindices",
    "abstractmethods",
    "atleast",
    "fracv",
    "Nystr",
    "pdiff",
    "Chatalic",
    "Schreuder",
    "Rudi",
    "Alessandro",
    "Rosasco",
    "eprint",
    "inproceedings",
    "improvedsgm",
    "Ermon",
    "Stefano",
    "Garg",
    "Sahaj",
    "Jiaxin",
    "PMLR",
    "Huszar",
    "Ferenc",
    "Duvenaud",
    "coresets",
    "Kbar",
    "rsample",
    "outpath",
    "softplus",
    "PRNG",
    "optax",
    "imageio",
    "dtype",
    "mimread",
    "minimising",
    "visualise",
    "elementwise",
    "vmapped",
    "initialisation",
    "pinv",
    "meshgrid",
    "devs",
    "egrad",
    "lpdf",
    "logpdf",
    "filesystems",
    "parseable",
    "isort",
    "pyproject",
    "pyroma",
    "pydocstyle",
    "argnames",
    "updatables",
    "argmax",
    "cand",
    "subkey",
    "nochange",
    "seealso",
    "SPHINXBUILD",
    "SOURCEDIR",
    "BUILDDIR",
    "SPHINXOPTS",
    "behaviour",
    "wmmd",
    "vmap",
    "rightarrow",
    "etils",
    "epath",
    "fsspec",
    "importlib",
    "jaxlib",
    "jaxopt",
    "joblib",
    "mdurl",
    "dtypes",
    "msgpack",
    "asyncio",
    "numpy",
    "einsum",
    "orbax",
    "protobuf",
    "pygments",
    "pyyaml",
    "scikit",
    "scipy",
    "tensorstore",
    "threadpoolctl",
    "toolz",
    "tqdm",
    "zipp",
    "exceptiongroup",
    "iniconfig",
    "pluggy",
    "initialises",
    "Annchor",
    "Nchor",
    "Gaussians",
    "sklearn",
    "kernelised",
    "targeting",
    "discerete",
    "mathbf",
    "xlarge",
    "chex",
    "pushd",
    "errorlevel",
    "popd",
    "sphinxcontrib",
    "typehints",
    "autosectionlabel",
    "intersphinx",
    "viewcode",
    "dollarmath",
    "amsmath",
    "bibfiles",
    "bysource",
    "undoc",
    "furo",
    "beautifulsoup",
    "certifi",
    "docutils",
    "idna",
    "imagesize",
    "latexcodec",
    "markupsafe",
    "mdit",
    "pybtex",
    "snowballstemmer",
    "soupsieve",
    "autodoc",
    "applehelp",
    "bibtex",
    "devhelp",
    "htmlhelp",
    "jsmath",
    "qthelp",
    "serializinghtml",
    "urllib",
    "arange",
    "nabla",
    "intercal",
    "bmatrix",
    "minimises",
    "colorama",
    "Vectorised",
    "Greedly",
    "fori",
    "linesearch",
    "argmin",
    "parallelised",
    "kdtree",
    "imread",
    "astype",
    "rpoints",
    "cmap",
    "cfgv",
    "contourpy",
    "distlib",
    "filelock",
    "fonttools",
    "kiwisolver",
    "matplotlib",
    "nodeenv",
    "opencv",
    "pipenv",
    "platformdirs",
    "pyparsing",
    "pyqt",
    "dateutil",
    "setuptools",
    "tomli",
    "virtualenv",
    "absl",
    "linalg",
    "lstsq",
    "Nystrom",
    "updateables",
    "Rademacher",
    "autodiff",
    "adamw",
    "minibatch",
    "adamw",
    "rgenerator",
    "OSQP",
    "mathrm",
    "Optimised",
    "ineq",
    "toctree",
    "genindex",
    "modindex",
    "functon",
    "figsize",
    "xlabel",
    "ylabel",
    "jumanjihouse",
    "unflatten"
  ]
