name: Bug Report
description: Report a problem
labels:
  - new
  - bug
projects:
  - gchq/16
body:
  - type: markdown
    attributes:
      value: >
        _Before reporting_: search [existing issues](https://github.com/gchq/coreax/issues)
        to see if an issue already exists for the bug you encountered.
  - type: textarea
    id: what-happened
    attributes:
      label: What's the problem?
      description: >
       What are you doing? What happens? How is this different from expected?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: How can we reproduce the issue?
      description: >
        List the steps to reproduce the behaviour. Include a [minimal, reproducible
        example](https://stackoverflow.com/help/minimal-reproducible-example) if
        possible. [Copy and paste code where possible rather than using screenshots
        ](https://meta.stackoverflow.com/a/285557/13990016), and put any code blocks
        inside triple backticks.
      placeholder: |
        1. Run '...'
        2. See error...
    validations:
      required: true
  - type: dropdown
    id: python-version
    attributes:
      label: Python version
      description: Which version or versions of Python are you seeing the problem on?
      multiple: true
      options:
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
    validations:
      required: true
  - type: input
    id: coreax-version
    attributes:
      label: Package version
      description: What version of Coreax are you using?
      placeholder: 0.1.0
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: Operating system
      description: What OS are you using? (Windows, Linux or Mac, and version)
      placeholder: Ubuntu 23.04.2
    validations:
      required: true
  - type: textarea
    id: other-packages
    attributes:
      label: Other packages
      description: >
       Are there any other packages in your environment not listed in the Coreax
       dependencies?
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: >
       Copy and paste any relevant log output. This is automatically formatted as code,
       so no backticks are required.
      render: shell
    validations:
      required: false
