name: Bug Report
description: Report a problem to us
title: "[Bug]: "
labels: ["bug", "new"]
body:
  - type: markdown
    attributes:
      value: |
        _Before reporting_: search [existing issues](https://github.com/gchq/coreax/issues). Below, * denotes a required field.
  - type: textarea
    attributes:
      label: "Problem*"
      description: "Provide a clear description of what the bug is"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to reproduce*"
      description: "List the steps needed to reproduce the issue"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected behaviour*"
      description: "Describe the behaviour you expect"
    validations:
      required: true
  - type: input
    attributes:
      label: "Python version*"
      placeholder: "3.10"
    validations:
      required: true
  - type: input
    attributes:
      label: "Package version*"
      description: "Detail the version of coreax you are using"
      placeholder: "1.0.0"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Operating system*"
      description: "Detail the operating system you are using (Windows, Linux, Mac, as-well as version)"
      placeholder: "Ubuntu 23.04.2"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Other packages in use"
      description: "List any other packages in use in your environment, that are not currently dependencies for coreax"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: "Code of Conduct*"
      description: "By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/gchq/coreax/blob/main/CODE_OF_CONDUCT.md)"
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true