name: Feature Request
description: Request a new feature in the codebase
title: "[Feature]: "
labels: ["enhancement", "new"]
body:
  - type: markdown
    attributes:
      value: |
        _Before reporting_: search [existing issues](https://github.com/gchq/coreax/issues). Below, * denotes a required field.
  - type: textarea
    attributes:
      label: "Is your proposal related to a problem?"
      description: "Provide a description of the problem this feature would solve (if applicable)."
      placeholder: "I'm always frustrated when..."
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Describe the solution you would like*"
      description: "Provide a clear and concise description of what you want to happen."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Describe alternatives you've considered"
      description: "Let us know about other solutions you've tried or researched. Is there already software that has the behavior you're interested in? What is it, and how does it work?"
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Additional context"
      description: "Is there anything else you can add about the proposal? You might want to link to related issues here, if you haven't already."
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: "Code of Conduct*"
      description: "By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/gchq/coreax/blob/main/CODE_OF_CONDUCT.md)"
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
