name: Build Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    env:
      # Disable implicitly syncing before running - we run an explicit sync first.
      UV_NO_SYNC: true
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Set up uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
        with:
          version: "latest"
          python-version: 3.14
          enable-cache: true
          cache-suffix: "docs"
      - name: Install documentation dependencies
        run: uv sync --group doc --no-dev --locked
      - name: Debug - uv pip freeze
        run: uv pip freeze
      - name: Build documentation
        run: |
          uv run -m sphinx -b html -aE -n -W --keep-going documentation/source documentation/build
      - name: Check external links
        run: |
          uv run -m sphinx -b linkcheck documentation/source documentation/build
