name: Build Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    env:
      # Disable implicitly syncing before running - we run an explicit sync first.
      UV_NO_SYNC: true
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - name: Set up uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990  # v8.3.2
        with:
          version: "latest"
          python-version: 3.14
          enable-cache: true
          cache-suffix: "docs"
      - name: Install documentation dependencies
        run: uv sync --group doc --no-dev --locked
      - name: Debug - uv pip freeze
        run: uv pip freeze
      - name: Build documentation
        run: |
          uv run -m sphinx -b html -aE -n -W --keep-going documentation/source documentation/build
      - name: Check external links
        run: |
          uv run -m sphinx -b linkcheck documentation/source documentation/build
