name: Build Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    env:
      # Disable implicitly syncing before running - we run an explicit sync first.
      UV_NO_SYNC: true
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      - name: Set up uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
        with:
          version: "latest"
          python-version: 3.14
          enable-cache: true
          cache-suffix: "docs"
      - name: Install documentation dependencies
        run: uv sync --group doc --no-dev --locked
      - name: Debug - uv pip freeze
        run: uv pip freeze
      - name: Build documentation
        run: |
          uv run -m sphinx -b html -aE -n -W --keep-going documentation/source documentation/build
      - name: Check external links
        run: |
          uv run -m sphinx -b linkcheck documentation/source documentation/build
